name: Publish kraft-shade
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests before publishing"
        required: true
        type: boolean
        default: false

jobs:
  publish:
    name: Publish
    uses: cardinalblue/github-actions/.github/workflows/publish-android-module-to-github.yaml@main
    with:
      target_module: "kraft-shade"
      run_tests: ${{ inputs.run_tests }}
